name: borders
description: Custom ShapeBorders like Chamfer Border,Trapezium border supported Animated.
version: 0.1.0
repository: https://github.com/shirne/flutter_borders.git

topics:
  - border
  - shape

screenshots: 
  - description: 'borders preview'
    path: preview/preview.gif

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:

