name: borders
description: Custom ShapeBorders like Dashed Border, Chamfer Border, Trapezium border supported Animation.
version: 0.4.0
repository: https://github.com/shirne/flutter_borders.git

topics:
  - border
  - shape
  - dashed

screenshots:
  - description: "borders preview"
    path: preview/preview.png

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
